### ISSUE TITLE
Bad Indent Issue

### ISSUE THREAD

**Issue by Pekum01** [phamleduy04/texas-dps-scheduler#116]
Getting this error code:

> texas-dps-scheduler@2.2.0 start
> ts-node --transpile-only src/index.ts

/workspaces/texas-dps-scheduler/node_modules/yaml/dist/compose/composer.js:69
                this.errors.push(new errors.YAMLParseError(pos, code, message));
                                 ^
YAMLParseError: All mapping items must start at the same column at line 41, column 1:

    # If the date input is invalid or in the past, the app will automatically u…
    startDate: ['05/31/2024']
^

    at Composer.onError (/workspaces/texas-dps-scheduler/node_modules/yaml/dist/compose/composer.js:69:34)
    at Object.resolveBlockMap (/workspaces/texas-dps-scheduler/node_modules/yaml/dist/compose/resolve-block-map.js:34:21)
    at resolveCollection (/workspaces/texas-dps-scheduler/node_modules/yaml/dist/compose/compose-collection.js:13:27)
    at Object.composeCollection (/workspaces/texas-dps-scheduler/node_modules/yaml/dist/compose/compose-collection.js:47:16)
    at composeNode (/workspaces/texas-dps-scheduler/node_modules/yaml/dist/compose/compose-node.js:31:38)
    at Object.resolveBlockMap (/workspaces/texas-dps-scheduler/node_modules/yaml/dist/compose/resolve-block-map.js:81:19)
    at resolveCollection (/workspaces/texas-dps-scheduler/node_modules/yaml/dist/compose/compose-collection.js:13:27)
    at Object.composeCollection (/workspaces/texas-dps-scheduler/node_modules/yaml/dist/compose/compose-collection.js:47:16)
    at Object.composeNode (/workspaces/texas-dps-scheduler/node_modules/yaml/dist/compose/compose-node.js:31:38)
    at Object.composeDoc (/workspaces/texas-dps-scheduler/node_modules/yaml/dist/compose/compose-doc.js:33:23) {
  code: 'BAD_INDENT',
  pos: [ 1803, 1804 ],
  linePos: [ { line: 41, col: 1 }, { line: 41, col: 2 } ]
}

**Comment by phamleduy04** [comment]
delete the `config.yml` file then copy it again
