### ISSUE TITLE
No Available location found

### ISSUE THREAD

**Issue by itsmateen** [phamleduy04/texas-dps-scheduler#162]
[08/07/2024 8:10:15] Loading personal info from environment variables.
[08/07/2024 8:10:15] WARNING -> Invalid date in config.yml, using current date
[08/07/2024 8:10:15] Texas Scheduler v4.1.0 is starting...
[08/07/2024 8:10:15] Requesting Available Location....
[08/07/2024 8:10:15] No captcha token found! Will try to get one....
[08/07/2024 8:10:16] Refreshed auth token: mZqurXtDSzwu6nuC883rrjztZPwQod381Qxq08TFTFAobG0ApMIBI/ZZMxArRCGX48UiznUPM2SzizugoZyDbt5T28F5DKi71UUk2qF88uGJhK9rlsMnR9G2DJkxlsdE5xDkIVYBANd3vwDR0aWoW+mfobLq16nEorpj1Qxxj9pWf2dm0Z8nGBJdVYP9sPQQ
[08/07/2024 8:10:16] WARNING -> No location found for zipcode: 75010
/home/runner/texas-dps-scheduler-1/src/Client/index.ts:163
            log.error(`No Available location found! Nearest location is ${response[0].Distance} miles away! Please change your config and try again!`);
                                                                                      ^
TypeError: Cannot read properties of undefined (reading 'Distance')
    at TexasScheduler.requestAvailableLocation (/home/runner/texas-dps-scheduler-1/src/Client/index.ts:163:87)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async TexasScheduler.run (/home/runner/texas-dps-scheduler-1/src/Client/index.ts:68:9)
npm notice 
npm notice New minor version of npm available! 10.5.0 -> 10.8.2
npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.8.2
npm notice Run npm install -g npm@10.8.2 to update!
npm notice

**Comment by Alecmay101** [comment]
Try adding some of the other nearby zipcodes. I used 75075 and got same error, but when i added an additional zipcode (75080) it worked for me

**Comment by phamleduy04** [comment]
Adding more zip codes will work. I will fix to show the error more useful

**Comment by yusufqxzi** [comment]
Just put in about 10 different zip codes it is still giving me the error.

**Comment by phamleduy04** [comment]
@yusufqxzi does it show logs like this format ```
WARNING -> No location found for zipcode: 12345
```

**Comment by gautham50050** [comment]
> Just put in about 10 different zip codes it is still giving me the error.

Hmm, I put a zipcode outside of my city and it worked just fine. But, zipcodes within my area was not working. Maybe have a a little distance or try the next town over.

**Comment by phamleduy04** [comment]
Try putting the city name instead of the zipcode to get better results. Mentioned [here](https://github.com/phamleduy04/texas-dps-scheduler/issues/150#issuecomment-2282282667)
