### ISSUE TITLE
Timeout error

### ISSUE THREAD

**Issue by sathwik1994** [phamleduy04/texas-dps-scheduler#164]
Getting the following error now:
```
texas-dps-scheduler@4.1.0 start
 ts-node --transpile-only src/index.ts

[08/08/2024 9:22:04] WARNING -> Invalid date in config.yml, using current date
[08/08/2024 9:22:04] Texas Scheduler v4.1.0 is starting...
[08/08/2024 9:22:04] Requesting Available Location....
[08/08/2024 9:22:04] Captcha token found: jKhyI8c3YOumT61TCwEpcbUsZZKEwH/R9ZI55VK3d6rzWdBwUxXIXJKYpGh6Ls70jW1e+pNzH1yUQNnXqCrMW3+bZI5nomt9BBJgev8Ds0w8CWY3Cngv73S0d0E7+RUp1MrIBSGsDL0afNQR/WDmKmpB8kmDr7xTGwZX6MNpT95ODTLoiu5cYWYiblS0vctQr6BNxzzr2vyHTkM8k+YsZA==
[08/08/2024 9:22:05] Refreshed auth token: I8LDBWyV6BwWxbK4Z1H3QWdAXGyUaI0Ag3XxOE3+BI50bBQWO0/CBnIssZ2UvLU9iyt7viRlpw4ogS2FwTq67GnBAw4UY+PMC/OWBcyu175a28f2u9MMDihHJ4MyAq1g1ocihtMU8mzLRHki4ang2/xl1v7e5rkm5a9uQF91BrUz9Mb+QzqIHSSWdeRWa2qPGWBtA/SoYtLrGU6dhyfg5HDs99h7Q1zfAzpDZoCxTn0=
/Users/sathwiknagulapati/texas-dps/texas-dps-scheduler/node_modules/undici/lib/dispatcher/client-h1.js:622
      util.destroy(socket, new HeadersTimeoutError())
                           ^
HeadersTimeoutError: Headers Timeout Error
    at Timeout.onParserTimeout [as callback] (/Users/sathwiknagulapati/texas-dps/texas-dps-scheduler/node_modules/undici/lib/dispatcher/client-h1.js:622:28)
    at Timeout.onTimeout [as _onTimeout] (/Users/sathwiknagulapati/texas-dps/texas-dps-scheduler/node_modules/undici/lib/util/timers.js:22:13)
    at listOnTimeout (node:internal/timers:573:17)
    at processTimers (node:internal/timers:514:7) {
  code: 'UND_ERR_HEADERS_TIMEOUT'
}

```

**Comment by phamleduy04** [comment]
try to increase header timeout value on config.yml, maybe 30000 or 40000
