### ISSUE TITLE
Config validation for manual token

### ISSUE THREAD

**Issue by phamleduy04** [phamleduy04/texas-dps-scheduler#181]
I am also getting this error. I am not using the paid solution. I am trying to use the manual token. I still have to put this part like this. "Browser" isn't working. @phamleduy04 
![image](https://github.com/user-attachments/assets/37b5196b-ed30-488a-ba7e-977de4079e55)

_Originally posted by @TracyZhou619 in https://github.com/phamleduy04/texas-dps-scheduler/issues/180#issuecomment-2565908917_

**Comment by Lilianeestbell** [comment]
@Lilianeestbell ➜ /workspaces/texas-dps-scheduler (main) $ npm run start

> texas-dps-scheduler@5.0.2 start
> ts-node --transpile-only src/index.ts

[01/01/2025 12:14:05] ERROR: Config file is not valid
ZodError: [
  {
    "received": "slover",
    "code": "invalid_enum_value",
    "options": [
      "browser",
      "solver"
    ],
    "path": [
      "appSettings",
      "captcha",
      "strategy"
    ],
    "message": "Invalid enum value. Expected 'browser' | 'solver', received 'slover'"
  }
]
    at Object.get error [as error] (/workspaces/texas-dps-scheduler/node_modules/zod/lib/types.js:55:31)
    at ZodObject.parse (/workspaces/texas-dps-scheduler/node_modules/zod/lib/types.js:131:22)
    at parseConfig (/workspaces/texas-dps-scheduler/src/Config/index.ts:28:26)
    at Object.<anonymous> (/workspaces/texas-dps-scheduler/src/CaptchaSolver/index.ts:8:27)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module.m._compile (/workspaces/texas-dps-scheduler/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Object.require.extensions.<computed> [as .ts] (/workspaces/texas-dps-scheduler/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1104:12) {
  issues: [
    {
      received: 'slover',
      code: 'invalid_enum_value',
      options: [Array],
      path: [Array],
      message: "Invalid enum value. Expected 'browser' | 'solver', received 'slover'"
    }
  ],
  addIssue: [Function (anonymous)],
  addIssues: [Function (anonymous)],
  errors: [
    {
      received: 'slover',
      code: 'invalid_enum_value',
      options: [Array],
      path: [Array],
      message: "Invalid enum value. Expected 'browser' | 'solver', received 'slover'"
    }
  ]
}
Hi , I got the same issues. It doesn't work because the captcha thing!

**Comment by phamleduy04** [comment]
Can you send your current config file with personal data removed? Thanks

**Comment by Lilianeestbell** [comment]
Thanks for reply. I just changed the configure as your tutorial. Then npm run start. The error message is as below. I tried github codespace and my local vscode, there are same error. Then I changed the appSettings:
  captcha:
    strategy: 'solver'
    solverOptions:
      solverService: 'capsolver'
      solverApiToken: 'my API Key'
into this, the error message changed into:
PS C:\Users\LilianeWang\Desktop\texas-dps-scheduler> npm run start

> texas-dps-scheduler@5.0.2 start
> ts-node --transpile-only src/index.ts

[01/01/2025 10:57:26] Texas Scheduler v5.0.2 is starting...
[01/01/2025 10:57:26] Requesting Available Location....
[01/01/2025 10:57:26] ERROR: ERROR_KEY_DENIED_ACCESS: Your api key is invalid or balance is insufficient (CAP-4E9EF7D13A69DC964BC196DF48B738C49EC47B747C0560A103922ED0830A43C0).
C:\Users\LilianeWang\Desktop\texas-dps-scheduler\src\CaptchaSolver\Capsolver.ts:30
        throw new Error(`Got ${getTaskID.statusCode} status code`);
              ^
Error: Got 401 status code
    at Object.CapSolverCreateTask (C:\Users\LilianeWang\Desktop\texas-dps-scheduler\src\CaptchaSolver\Capsolver.ts:30:15)       
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async TexasScheduler.getCatpchaToken (C:\Users\LilianeWang\Desktop\texas-dps-scheduler\src\Client\index.ts:445:31)       
    at async TexasScheduler.getAuthToken (C:\Users\LilianeWang\Desktop\texas-dps-scheduler\src\Client\index.ts:418:34)
    at async TexasScheduler.run (C:\Users\LilianeWang\Desktop\texas-dps-scheduler\src\Client\index.ts:65:93)
PS C:\Users\LilianeWang\Desktop\texas-dps-scheduler> 
**here is the config file when 401 error is showing up:**
personalInfo:
  # Load from environment secret to prevent personal info leaking
  # If you are using replit free plan, set this true
  # Then add your info to the secrets section
  loadFromEnv: false

  # if loadFromEnv is true, anything in personalInfo beside typeId is ignored
  firstName: 'John'
  lastName: 'Wong'
  # Date of birth (MM/DD/YYYY)
  dob: 'date'
  # Use real email to get appointment infomation
  email: 'email'
  # Not really needed but good to have a real one
  lastFourSSN: '1001'
  # If you want to recieve notificaion through phone, if not keep blank
  # WARNING: Use number only (Ex: 111111111)~~
  phoneNumber: ''

  # Serivce you needed at DPS. Check the full list on https://github.com/phamleduy04/texas-dps-scheduler/wiki/TypeId-list
  # If you need to apply for Texas DL you don't need to change it
  typeId: 71

location:
  # Search DPS Locations by City Name, if City name is given, zipCode is ignored.
  # If you don't want to search by city name, set it to ['']
  cityName: ['']
  # Zipcode of your location. Can add more DPS location by using ',' for multiple zipcode
  zipCode: ['75232', '75050']
  # Choose your DPS location by yourself when running the application if set to true
  pickDPSLocation: false
  # Get appointment from all DPS location by distance from the zipcode, will auto skip this when pickDPSLocation is true
  miles: 15
  # Put empty [''] for any day
  # DPS is closed on weekends, so you can't book on Saturday and Sunday
  preferredDays: ['']
  # Put true/false without quotes if you want to book only same day appointment
  sameDay: false
  # Put how many day from today you want to book from start to end (7 is a good number)
  daysAround:
    ## Start date: start and end will start counting from this date
    # MM/DD/YYYY format, if blank will use current date
    # If the date input is invalid or in the past, the app will automatically use the current date as start date
    startDate: null
    start: 0
    end: 7
  # Put what time you want to book
  timesAround:
    # Number in 24h format, start = 6 and end = 18 means get appointment between 6 AM - 6 PM
    start: 6
    end: 18

appSettings:
  # Keep this empty, if it didnt work for you, use the wiki below to obtain one
  # https://github.com/phamleduy04/texas-dps-scheduler/wiki/How-to-get-Auth-Token
  authToken: ''
  # Put true/false without quotes if you want to cancel the appointment automatically if found existing appointment
  cancelIfExist: false
  # The time interval (in ms) the app will recheck for newer dates
  interval: 10000
  # Set this to true if you using replit, heroku or something equivalent
  webserver: false
  # Set this to higher if you encounter Header Timeout error. This one is in miliseconds
  headersTimeout: 30000 
  # How many times to retry if the request to DPS server failled
  maxRetry: 3
  # Read this for more infomation: https://github.com/phamleduy04/texas-dps-scheduler/wiki/Captcha-(Auth-Token)
  captcha:
    # Avaliable options: solver or browser
    strategy: 'solver'
    solverOptions:
      # Avaliable options: capsolver
      solverService: 'capsolver'
      solverApiToken: 'CAP-4E9EF7D13A69DC964BC196DF48B738C49EC47B747C0560A103922ED0830A43C0'
  # ntfy.sh push notification
  pushNotifcation:
    enabled: false
    baseURL: ''
    topicName: ''
    token: ''
    My current solution is to buy Capsolver service. But i don't know if it is the right solution. Please help me with that. Thanks!

**Comment by phamleduy04** [comment]
@Lilianeestbell 

ERROR: ERROR_KEY_DENIED_ACCESS: Your api key is invalid or balance is insufficient (CAP-4E9EF7D13A69DC964BC196DF48B738C49EC47B747C0560A103922ED0830A43C0)

this api key is invalid / no balance, can you make sure your key is correct

**Comment by kiranchinta23** [comment]
<img width="1464" alt="Screenshot 2025-01-01 at 7 36 43 PM" src="https://github.com/user-attachments/assets/a3972f62-e80a-42bb-ab3b-b313faa54f66" />
same issue for me, i ran in codespace

**Comment by phamleduy04** [comment]
@kiranchinta23 can you put `capsolver` to solverService option?

**Comment by phamleduy04** [comment]
Also if you trying to do browser strategy on codespace it will not work.

**Comment by Lilianeestbell** [comment]
> @kiranchinta23 can you put `capsolver` to solverService option?

if put `capsolver` to solverService option, you have to get right apikey, which requires you to pay for it.

**Comment by Lilianeestbell** [comment]
> @Lilianeestbell
> 
> ERROR: ERROR_KEY_DENIED_ACCESS: Your api key is invalid or balance is insufficient (CAP-4E9EF7D13A69DC964BC196DF48B738C49EC47B747C0560A103922ED0830A43C0)
> 
> this api key is invalid / no balance, can you make sure your key is correct

Hi, if i pay for it and make sure my key is right, then the project will work? have you tried that?

**Comment by phamleduy04** [comment]
yes, or you can do manual mode which does not require an api key. I will update the wiki with further instructions.

https://github.com/phamleduy04/texas-dps-scheduler/wiki/How-to-get-Auth-Token

**Comment by Lilianeestbell** [comment]
Thanks. It works well now when I use the manual auth according to your new tutorial!

**Comment by phamleduy04** [comment]
The token will expire after 20 minutes. Im developing a new version when the token expire it will prompt you for a new token.

**Comment by Lilianeestbell** [comment]
The token will expire after 10 minutes. Thanks for your hep with that! That's really helpful!
