### ISSUE TITLE
Running with docker compose

### ISSUE THREAD

**Issue by camilonova** [phamleduy04/texas-dps-scheduler#67]
I cloned the repository, edited config.yml, and ran `docker compose up` on an M1 MacBook Pro.

I got this error:

```
[+] Running 1/0
 ✔ Container texas-dps-scheduler  Created                                                                                                                                             0.0s
Attaching to texas-dps-scheduler
texas-dps-scheduler  | node:internal/modules/cjs/loader:1051
texas-dps-scheduler  |   throw err;
texas-dps-scheduler  |   ^
texas-dps-scheduler  |
texas-dps-scheduler  | Error: Cannot find module 'tslib'
texas-dps-scheduler  | Require stack:
texas-dps-scheduler  | - /home/container/index.js
texas-dps-scheduler  |     at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
texas-dps-scheduler  |     at Module._load (node:internal/modules/cjs/loader:901:27)
texas-dps-scheduler  |     at Module.require (node:internal/modules/cjs/loader:1115:19)
texas-dps-scheduler  |     at require (node:internal/modules/helpers:130:18)
texas-dps-scheduler  |     at Object.<anonymous> (/home/container/index.js:3:17)
texas-dps-scheduler  |     at Module._compile (node:internal/modules/cjs/loader:1233:14)
texas-dps-scheduler  |     at Module._extensions..js (node:internal/modules/cjs/loader:1287:10)
texas-dps-scheduler  |     at Module.load (node:internal/modules/cjs/loader:1091:32)
texas-dps-scheduler  |     at Module._load (node:internal/modules/cjs/loader:938:12)
texas-dps-scheduler  |     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12) {
texas-dps-scheduler  |   code: 'MODULE_NOT_FOUND',
texas-dps-scheduler  |   requireStack: [ '/home/container/index.js' ]
texas-dps-scheduler  | }
texas-dps-scheduler  |
texas-dps-scheduler  |
texas-dps-scheduler  | Node.js v20.5.1
texas-dps-scheduler  |
texas-dps-scheduler exited with code 1
```

**Comment by phamleduy04** [comment]
Please try pull the new image and see if the issue fixed. Also please make sure `pickDPSLocation` is set to false if using docker :)

**Comment by Awdball** [comment]
Thanks for the quick update! I was getting this same error as well.
pickDPSLocation is set to false.
New image has been pulled and now fails with the following:

```
docker logs texas-dps-scheduler
node:internal/modules/cjs/loader:1051
  throw err;
  ^

Error: Cannot find module '../../package.json'
Require stack:
- /home/container/Client/index.js
- /home/container/index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at Module._load (node:internal/modules/cjs/loader:901:27)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (/home/container/Client/index.js:14:21)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/container/Client/index.js', '/home/container/index.js' ]
}

Node.js v20.6.0
```

**Comment by phamleduy04** [comment]
Please try the new image and new docker-compose file to work. Tested on Ubuntu 22.04.2 LTS:

```
sudo docker-compose up
Recreating texas-dps-scheduler ... done
Attaching to texas-dps-scheduler
texas-dps-scheduler | [09/06/2023 6:46:12] Texas Scheduler v1.6.5 is starting...
texas-dps-scheduler | [09/06/2023 6:46:12] Requesting Avaliable Location....
texas-dps-scheduler | [09/06/2023 6:46:19] Found 5 avaliable location that match your criteria
texas-dps-scheduler | [09/06/2023 6:46:19] Lewisville, Carrollton Mega Center, Flower Mound, Denton, Plano
texas-dps-scheduler | [09/06/2023 6:46:19] Checking Avaliable Location Dates....
texas-dps-scheduler | --------------------------------------------------------------------------------
texas-dps-scheduler | [09/06/2023 6:46:25] Lewisville is not avaliable in around 0-7 days from today!
^CGracefully stopping... (press Ctrl+C again to force)
Stopping texas-dps-scheduler   ... done
```

**Comment by Awdball** [comment]
This is now running properly for me on my Arch Linux host as well as an Ubuntu 22.04 testing VM. 

Thank you!

**Comment by phamleduy04** [comment]
@camilonova I don't think I did an image for arm64, but can you check if its working and does it running natively with apple silicon?

**Comment by camilonova** [comment]
I got this:

>dps-scheduler The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

**Comment by phamleduy04** [comment]
try to pull the newest image, i did push a new `linux/arm64` image

**Comment by camilonova** [comment]
It pulled ok, but now it gave me this error:

<img width="673" alt="CleanShot 2023-09-11 at 11 10 43@2x" src="https://github.com/phamleduy04/texas-dps-scheduler/assets/202559/9c4c6ed0-b35c-48ad-8def-b42e2e6bd41a">

**Comment by phamleduy04** [comment]
Did you tried the new `docker-compose.yml`? I updated the file along with the multi-arch image
