### ISSUE TITLE
Error on npm run start 

### ISSUE THREAD

**Issue by drgrabowski** [phamleduy04/texas-dps-scheduler#97]
Received the following on npm run start. Running on Ubuntu, fresh install of nodejs and first clone of this project. Tried removing node_mondules and package-lock.json and re-do the install, same error.

> texas-dps-scheduler@1.6.8 start
> ts-node --transpile-only src/index.ts

/home/<redacted>/github/texas-dps-scheduler/node_modules/typescript/lib/typescript.js:139
    for (let i = startIndex ?? 0; i < array.length; i++) {
                             ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at attemptRequireWithV8CompileCache (/home/<redacted>/github/texas-dps-scheduler/node_modules/ts-node/dist/util.js:104:16)
    at loadCompiler (/home/<redacted>/github/texas-dps-scheduler/node_modules/ts-node/dist/configuration.js:237:56)
    at resolveAndLoadCompiler (/home/<redacted>/github/texas-dps-scheduler/node_modules/ts-node/dist/configuration.js:226:16)

**Comment by drgrabowski** [comment]
Yep, that did it. I did not realize that Ubuntu was so far behind, my Homebridge instance uses it's own version of Node. Thanks!

**Comment by phamleduy04** [comment]
great! glad i can help u 👍
